# Exponential Decay

$$
\begin{align}
\frac {dY}{dt} &= -\lambda Y \\
dy &= -\lambda Y dt \\
\frac {dY}{Y} &= -\lambda dt
\end {align}
$$

Integrate both sides to get:
$$
\begin{align}
ln(Y(t)) &= -\lambda t + C \\
Y(t) &= e^{-\lambda t}e^C
\end{align}
$$

At $t=0$, $Y=Y_0$, so $e^C = Y_0$. Substituting, the equation above becomes:

$$
Y(t) = Y_0 e^{-\lambda t}
$$

Let's compare the above result with what we get from `scipy.integrate.solve_ivp`

In [2]:
import numpy as np
from scipy.integrate import solve_ivp 

In [3]:
def exponential_decay(t,y, lmbda):
    return -lmbda*y

In [4]:
#integrate to get the solution over a range:
t_rng = [0,10]
lmbda = 0.5
Y_0 = 2.0

sol = solve_ivp(exponential_decay, t_rng, [Y_0],args=[lmbda],t_eval=np.arange(10))

In [5]:
sol.t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
sol.y

array([[2.        , 1.21305368, 0.73534013, 0.44651426, 0.2706912 ,
        0.16433318, 0.09965105, 0.06047056, 0.03669163, 0.02225507]])

In [7]:
#calculate Y by hand using the t values returned from the integrator
t = sol.t
Y = Y_0 *np.exp(-lmbda*t)

In [8]:
print(Y)
print( sol.y)

[2.         1.21306132 0.73575888 0.44626032 0.27067057 0.16417
 0.09957414 0.06039477 0.03663128 0.02221799]
[[2.         1.21305368 0.73534013 0.44651426 0.2706912  0.16433318
  0.09965105 0.06047056 0.03669163 0.02225507]]


In [9]:
np.allclose (Y , sol.y)

False

The results are the same to within 4 significant digits; probably messing around with tolerance parameters in the solver could get them to be closer -- but good enough for the time being!!

In [18]:
def exponential_decay_2d(t, y, lmbdas):
    Y = np.zeros_like(y)
    for i in range(len(Y)):
        Y[i] = -1*lmbdas[i]*y[i]
    return Y

In [19]:
lmbdas = np.array([0.7, 0.5])
Y_0 = np.array([4,3])
t_span = [0,10]
t_eval = np.arange(10)

sol = solve_ivp(exponential_decay_2d, t_span, Y_0, args=[lmbdas], t_eval=t_eval)

In [20]:
sol.t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
sol.y

array([[4.        , 1.98638957, 0.98585099, 0.49002117, 0.24365827,
        0.12102913, 0.0600915 , 0.02986639, 0.01485104, 0.00737624],
       [3.        , 1.81959218, 1.10355136, 0.66939535, 0.40606872,
        0.24629844, 0.14938187, 0.09061181, 0.05496707, 0.03333965]])